# Generated by Django 5.1.3 on 2024-11-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('total_lots', models.IntegerField()),
                ('total_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='developments/')),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Lotes.development')),
            ],
        ),
    ]
